"""
Multiword expression dictionary mapping original lemmas to their normalized forms.
"""

MULTIWORD_EXPRESSIONS = {
    'i_tak_dalej': 'i_tak_dalej',
    'i tak dalej': 'i_tak_dalej',
    'i tak dalej': 'i_tak_dalej',
    'i tym podobne': 'i_tym_podobne',
    'i_tym_podobne': 'i_tym_podobne',
    'i tym podobne': 'i_tym_podobne',
    'to_jest': 'to_jest',
    'to jest': 'to_jest',
    'to jest': 'to_jest',
    'na_przykład': 'na_przykład',
    'na przykład': 'na_przykład',
    'na przykład': 'na_przykład',
    'tak_zwany': 'tak_zwany',
    'tak zwany': 'tak_zwany',
    'tak zwany': 'tak_zwany',
    'między innymi': 'między_innymi',
    'między_innymi': 'między_innymi',
    'między innymi': 'między_innymi',
    'bieżącego_rok': 'bieżący_rok',
    'bieżącego rok': 'bieżący_rok',
    'bieżącego rok': 'bieżący_rok',
    'bieżący_rok': 'bieżący_rok',
    'bieżący rok': 'bieżący_rok',
    'bieżący rok': 'bieżący_rok',
    'do_spraw': 'do_spraw',
    'do spraw': 'do_spraw',
    'do spraw': 'do_spraw',
    'w_sprawie': 'w_sprawie',
    'w sprawie': 'w_sprawie',
    'w sprawie': 'w_sprawie',
    'na_temat': 'na_temat',
    'na temat': 'na_temat',
    'na temat': 'na_temat',
    'pod tytułem': 'pod_tytułem',
    'pod_tytułem': 'pod_tytułem',
    'pod tytułem': 'pod_tytułem',
    'bieżący_miesiąc': 'bieżący_miesiąc',
    'bieżący miesiąc': 'bieżący_miesiąc',
    'bieżący miesiąc': 'bieżący_miesiąc',
    'post_scriptum': 'post_scriptum',
    'post scriptum': 'post_scriptum',
    'post scriptum': 'post_scriptum',
    'to_znaczy': 'to_znaczy',
    'to znaczy': 'to_znaczy',
    'to znaczy': 'to_znaczy',
    'pod_nazwą': 'pod_nazwą',
    'pod nazwą': 'pod_nazwą',
    'pod nazwą': 'pod_nazwą',
    'ubiegły_rok': 'ubiegły_rok',
    'ubiegły rok': 'ubiegły_rok',
    'ubiegły rok': 'ubiegły_rok',
    'spółka akcyjna': 'spółka_akcyjna',
    'spółka_akcyjna': 'spółka_akcyjna',
    'spółka akcyjna': 'spółka_akcyjna',
    'świętej_pamięci': 'świętej_pamięci',
    'świętej pamięci': 'świętej_pamięci',
    'świętej pamięci': 'świętej_pamięci',
    'kilometr_kwadratowy': 'kilometr_kwadratowy',
    'kilometr kwadratowy': 'kilometr_kwadratowy',
    'kilometr kwadratowy': 'kilometr_kwadratowy',
    'pod_wezwaniem': 'pod_wezwaniem',
    'pod wezwaniem': 'pod_wezwaniem',
    'pod wezwaniem': 'pod_wezwaniem',
    'nad_poziomem_morza': 'nad_poziomem_morza',
    'nad poziomem morza': 'nad_poziomem_morza',
    'nad poziomem morza': 'nad_poziomem_morza',
    'ograniczona_odpowiedzialność': 'ograniczona_odpowiedzialność',
    'ograniczona odpowiedzialność': 'ograniczona_odpowiedzialność',
    'ograniczona odpowiedzialność': 'ograniczona_odpowiedzialność',
    'Immunoglobina_E': 'Immunoglobina_E',
    'Immunoglobina E': 'Immunoglobina_E',
    'Immunoglobina E': 'Immunoglobina_E',
    'wyżej_wymieniony': 'wyżej_wymieniony',
    'wyżej wymieniony': 'wyżej_wymieniony',
    'wyżej wymieniony': 'wyżej_wymieniony',
    'przed_naszą_erą': 'przed_naszą_erą',
    'przed naszą_erą': 'przed_naszą_erą',
    'przed naszą_erą': 'przed_naszą_erą'
}
